name: cyber_discovery
description: Never miss a deadline again and keep up with the latest meme culture with the UNOFFICIAL Cyber Discovery App.

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: "^0.2.4"
  firebase_database: "^2.0.0"
  firebase_messaging: "^1.0.2"
  firebase_analytics: "^1.0.1"

  # Other Dependencies
  cached_network_image: "^0.4.1"
  flutter_cache_manager: "^0.1.1"
  audioplayers: "^0.7.7"
  xml: "^3.0.0"
  html2md: "^0.2.1"
  flutter_markdown: "^0.2.0"
  intl: "^0.15.6"
  url_launcher: "^3.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Images
  assets:
    - assets/images/drawer_head.png
    - assets/images/unreleased.png
    - assets/images/error_image.png
    - assets/images/contributors.png
  # Fonts
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/dosis_regular.ttf
          style: normal
        - asset: fonts/dosis_semibold.ttf
          weight: 600